version: '3.8'

services:
  db:
    image: postgres:13
    container_name: taskmanager-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge
